if(NOT DEFINED INTRO OR NOT EXISTS "${INTRO}")
    message(FATAL_ERROR "Intro executable was not produced: ${INTRO}")
endif()
if(NOT DEFINED MAX_BYTES OR NOT MAX_BYTES MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "MAX_BYTES must be a positive integer.")
endif()
file(SIZE "${INTRO}" intro_bytes)
message(STATUS "Intro size: ${intro_bytes} bytes; allowed maximum: ${MAX_BYTES} bytes")
if(intro_bytes GREATER MAX_BYTES)
    message(FATAL_ERROR "${INTRO} is ${intro_bytes} bytes, exceeding the ${MAX_BYTES}-byte limit.")
endif()
